# Generated by Django 4.2.6 on 2023-10-24 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
    ]
